coincap:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: admin
      password: admin
      port: 5432
      dbname: coincap
      schema: coincap_raw
      threads: 1